# applicaion
 
## Application [/admin/getApplication]
 
### List all applications [GET]
+ Response 200 (application/json)
[
     {
      appID:"2234",
      studentID: "40382684",
      first_name: "John",
      last_name: "Doe",
      answer1:"I got an A",
      answer2:"5"
      answer3:"6"
      classes: ["CSE 1342", "CSE 4348", "CSE 2341"],
      times: ["MWF 12 - 2", "TTh 5 -7"]
    },
    {
      appID:"4321"
      studentID: "12345678",
      first_name: "Dohn",
      last_name: "Joe",
      answer1:"I got an A-",
      answer2:"8"
      answer3:"9"
      classes: ["CSE 1341", "KNW 2300", "CSE 1342"],
      times: ["MW 12 - 3", "T 6 -9"]
    }
 
] 
 
##applications [/admin/getApplication/{id}]
### get application by id[GET]

+ Parameters
  + id - application id

+ Response 200 (application/json)
  {
    appID:"4321"
      studentID: "12345678",
      first_name: "Dohn",
      last_name: "Joe",
      answer1:"I got an A-",
      answer2:"8"
      answer3:"9"
      classes: ["CSE 1341", "KNW 2300", "CSE 1342"],
      times: ["MW 12 - 3", "T 6 -9"]
  }
 
##applications [/admin/getApplication/{id}/status]
### update application status[POST]

+ Parameters
  + id - application id
  + status
  +Response 200
  {
  status:"accepted"
  
  }
##applications [/admin/getApplication/{id}]
### delete application by id [POST]
+ Parameters
  + id - application id
