-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 23:11:22 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tutors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tutors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tutors` (
  `tutor_id` INT NOT NULL,
  `tutor_first_name` VARCHAR(45) NULL COMMENT '	',
  `tutor_last_name` VARCHAR(45) NULL,
  `tutor_email` VARCHAR(45) NULL,
  `tutor_phone` VARCHAR(45) NULL,
  `tutor_gpa` DECIMAL(3) NULL,
  `tutor_major` VARCHAR(45) NULL,
  PRIMARY KEY (`tutor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Timeslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Timeslots` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Timeslots` (
  `timeslot_id` INT NOT NULL,
  `timeslot_time` VARCHAR(45) NULL,
  `Tutors_tutor_id` INT NOT NULL,
  PRIMARY KEY (`timeslot_id`),
  INDEX `fk_Timeslots_Tutors1_idx` (`Tutors_tutor_id` ASC),
  CONSTRAINT `fk_Timeslots_Tutors1`
    FOREIGN KEY (`Tutors_tutor_id`)
    REFERENCES `mydb`.`Tutors` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sessions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Sessions` (
  `session_id` INT NOT NULL,
  `session_date` DATE NULL,
  `session_time` VARCHAR(45) NULL,
  `Tutors_tutor_id` INT NOT NULL,
  `student_id` VARCHAR(45) NULL,
  `student_email` VARCHAR(45) NULL,
  `session_start_time` VARCHAR(45) NULL,
  `session_end_time` VARCHAR(45) NULL,
  `student_first_name` VARCHAR(45) NULL,
  `student_last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`session_id`),
  INDEX `fk_Sessions_Tutors_idx` (`Tutors_tutor_id` ASC),
  CONSTRAINT `fk_Sessions_Tutors`
    FOREIGN KEY (`Tutors_tutor_id`)
    REFERENCES `mydb`.`Tutors` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Applicants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Applicants` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Applicants` (
  `applicant_id` INT NOT NULL,
  `applicant_first_name` VARCHAR(45) NULL,
  `applicant_last_name` VARCHAR(45) NULL,
  `applicant_email` VARCHAR(45) NULL,
  `applicant_gpa` DECIMAL(3) NULL,
  `applicant_major` VARCHAR(45) NULL,
  `application_status` TINYINT(1) NULL,
  `applicant_password` VARCHAR(45) NULL,
  PRIMARY KEY (`applicant_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ApplicantTimeslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ApplicantTimeslots` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ApplicantTimeslots` (
  `timeslot_id` INT NOT NULL,
  `timeslot_time` VARCHAR(45) NULL,
  `Applicants_applicant_id` INT NOT NULL,
  PRIMARY KEY (`timeslot_id`),
  INDEX `fk_ApplicantTimeslots_Applicants1_idx` (`Applicants_applicant_id` ASC),
  CONSTRAINT `fk_ApplicantTimeslots_Applicants1`
    FOREIGN KEY (`Applicants_applicant_id`)
    REFERENCES `mydb`.`Applicants` (`applicant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reviews` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reviews` (
  `review_id` INT NOT NULL,
  `score_helpfulness` INT NULL,
  `score_clarity` INT NULL,
  `score_friendlynes` INT NULL,
  `Sessions_session_id` INT NOT NULL,
  `score_avg` INT NULL,
  `review_comments` VARCHAR(500) NULL,
  PRIMARY KEY (`review_id`),
  INDEX `fk_Reviews_Sessions1_idx` (`Sessions_session_id` ASC),
  CONSTRAINT `fk_Reviews_Sessions1`
    FOREIGN KEY (`Sessions_session_id`)
    REFERENCES `mydb`.`Sessions` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `user_id` INT NOT NULL,
  `password` VARCHAR(45) NULL,
  `hash` VARCHAR(45) NULL,
  `salt` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admins` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Admins` (
  `admin_id` INT NOT NULL,
  `admin_first_name` VARCHAR(45) NULL,
  `admin_last_name` VARCHAR(45) NULL,
  `admin_email` VARCHAR(45) NULL,
  `admin_phone` VARCHAR(45) NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TutorClasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TutorClasses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TutorClasses` (
  `tutorclass_id` INT NOT NULL,
  `class_name` VARCHAR(45) NULL,
  `class_gpa` DECIMAL(3) NULL,
  `Tutors_tutor_id` INT NOT NULL,
  PRIMARY KEY (`tutorclass_id`),
  INDEX `fk_TutorClasses_Tutors1_idx` (`Tutors_tutor_id` ASC),
  CONSTRAINT `fk_TutorClasses_Tutors1`
    FOREIGN KEY (`Tutors_tutor_id`)
    REFERENCES `mydb`.`Tutors` (`tutor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ApplicantClasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ApplicantClasses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ApplicantClasses` (
  `idApplicantClasses` INT NOT NULL,
  `class_name` VARCHAR(45) NULL,
  `class_gpa` DECIMAL(3) NULL,
  `Applicants_applicant_id` INT NOT NULL,
  PRIMARY KEY (`idApplicantClasses`),
  INDEX `fk_ApplicantClasses_Applicants1_idx` (`Applicants_applicant_id` ASC),
  CONSTRAINT `fk_ApplicantClasses_Applicants1`
    FOREIGN KEY (`Applicants_applicant_id`)
    REFERENCES `mydb`.`Applicants` (`applicant_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
