-- MySQL Script generated by MySQL Workbench
-- Sat Apr 23 23:48:35 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tutors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tutors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Tutors` (
  `tutor_id` INT NOT NULL,
  `tutor_first_name` VARCHAR(45) NULL COMMENT '	',
  `tutor_last_name` VARCHAR(45) NULL,
  `tutor_email` VARCHAR(45) NULL,
  `tutor_phone` VARCHAR(45) NULL,
  `tutor_gpa` DECIMAL(3) NULL,
  `tutor_major` VARCHAR(45) NULL,
  PRIMARY KEY (`tutor_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Timeslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Timeslots` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Timeslots` (
  `timeslot_id` INT NOT NULL,
  `timeslot_time` VARCHAR(45) NULL,
  `Tutors_tutor_id` INT NOT NULL,
  `timeslot_day` VARCHAR(45) NULL,
  PRIMARY KEY (`timeslot_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sessions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Sessions` (
  `session_id` INT NOT NULL,
  `session_date` DATE NULL,
  `session_time` VARCHAR(45) NULL,
  `Tutors_tutor_id` INT NOT NULL,
  `student_id` VARCHAR(45) NULL,
  `student_email` VARCHAR(45) NULL,
  `session_start_time` VARCHAR(45) NULL,
  `session_end_time` VARCHAR(45) NULL,
  `student_first_name` VARCHAR(45) NULL,
  `student_last_name` VARCHAR(45) NULL,
  PRIMARY KEY (`session_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Applicants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Applicants` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Applicants` (
  `applicant_id` INT NOT NULL,
  `applicant_first_name` VARCHAR(45) NULL,
  `applicant_last_name` VARCHAR(45) NULL,
  `applicant_email` VARCHAR(45) NULL,
  `applicant_gpa` DECIMAL(3) NULL,
  `applicant_major` VARCHAR(45) NULL,
  `application_status` VARCHAR(45) NULL,
  `applicant_hash` VARCHAR(60) NULL,
  PRIMARY KEY (`applicant_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ApplicantTimeslots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ApplicantTimeslots` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ApplicantTimeslots` (
  `timeslot_id` INT NOT NULL,
  `timeslot_time` VARCHAR(45) NULL,
  `Applicants_applicant_id` INT NOT NULL,
  `timeslot_day` VARCHAR(45) NULL,
  PRIMARY KEY (`timeslot_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reviews` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Reviews` (
  `review_id` INT NOT NULL,
  `score_helpfulness` INT NULL,
  `score_clarity` INT NULL,
  `score_friendlynes` INT NULL,
  `Sessions_session_id` INT NOT NULL,
  `score_avg` INT NULL,
  `review_comments` VARCHAR(500) NULL,
  PRIMARY KEY (`review_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `user_id` INT NOT NULL,
  `hash` VARCHAR(45) NULL,
  `admin` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admins` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`Admins` (
  `admin_id` INT NOT NULL,
  `admin_first_name` VARCHAR(45) NULL,
  `admin_last_name` VARCHAR(45) NULL,
  `admin_email` VARCHAR(45) NULL,
  `admin_phone` VARCHAR(45) NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TutorClasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TutorClasses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TutorClasses` (
  `tutorclass_id` INT NOT NULL,
  `class_type` VARCHAR(4) NULL,
  `class_num` VARCHAR(4) NULL,
  `class_grade` VARCHAR(3) NULL,
  `Tutors_tutor_id` INT NOT NULL,
  PRIMARY KEY (`tutorclass_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`ApplicantClasses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ApplicantClasses` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`ApplicantClasses` (
  `idApplicantClasses` INT NOT NULL,
  `class_type` VARCHAR(4) NULL,
  `class_num` VARCHAR(4) NULL,
  `class_grade` VARCHAR(3) NULL,
  `Applicants_applicant_id` INT NOT NULL,
  PRIMARY KEY (`idApplicantClasses`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`TutorRequests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TutorRequests` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`TutorRequests` (
  `tr_id` INT NOT NULL AUTO_INCREMENT,
  `tr_tutor_id` INT NULL,
  `tr_classtype` VARCHAR(4) NULL,
  `tr_classnum` VARCHAR(4) NULL,
  `Tutors_tutor_id` INT NOT NULL,
  `tr_request_type` VARCHAR(4) NULL,
  PRIMARY KEY (`tr_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
